#!/usr/bin/env bash
# Install the personal rules in this folder as every agent's global instructions.
#
#   bash global/install.sh                          # install, or update after an edit
#   bash global/install.sh --dry-run                # show what install would change
#   bash global/install.sh --uninstall              # remove what install made and restore the backups
#   bash global/install.sh --uninstall --dry-run    # show what uninstall would change
#
# ~/.agents/AGENTS.md is generated from global/AGENTS.md (public) plus global/AGENTS.local.md
# (private, ignored by git) when it exists. Run install again after you edit either file.
# Every file install replaces is kept as <file>.bak.<timestamp>; uninstall restores the newest one.
set -euo pipefail

usage() { sed -n '4,7p' "$0" | sed 's/^# //' >&2; exit 2; }

DRY_RUN=0
UNINSTALL=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --uninstall) UNINSTALL=1 ;;
    *) echo "Unknown argument: $arg" >&2; usage ;;
  esac
done

DIR="$(cd "$(dirname "$0")" && pwd)"
PUBLIC="$DIR/AGENTS.md"
LOCAL="$DIR/AGENTS.local.md"
CANON="$HOME/.agents/AGENTS.md"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
IMPORT_LINE="@~/.agents/AGENTS.md"
CLAUDE_CONTENT="$(printf '# Global instructions\n\nThe shared rules for all agents live in ~/.agents/AGENTS.md.\n\n%s' "$IMPORT_LINE")"
HEADER="<!-- Generated by onchainpm-harness global/install.sh. Do not edit. Edit global/AGENTS.md or global/AGENTS.local.md, then run the install again. -->"
STAMP="$(date +%Y%m%d%H%M%S)"

[ -f "$PUBLIC" ] || { echo "Missing $PUBLIC" >&2; exit 2; }

run() { if [ "$DRY_RUN" = 1 ]; then echo "  would: $*"; else "$@"; fi; }
newest_backup() { { ls -1 "$1".bak.* 2>/dev/null || true; } | sort | tail -1; }
is_generated() { [ -f "$1" ] && [ ! -L "$1" ] && [ "$(head -1 "$1")" = "$HEADER" ]; }

backup() { # backup <file>: keep any existing file or link before it is replaced
  if [ -e "$1" ] || [ -L "$1" ]; then
    run cp -P "$1" "$1.bak.$STAMP"
    echo "backup  $1.bak.$STAMP"
    run rm "$1"
  fi
}

link() { # link <target> <points-to>
  local target="$1" dest="$2"
  if [ -L "$target" ] && [ "$(readlink "$target")" = "$dest" ]; then
    echo "ok      $target"; return
  fi
  run mkdir -p "$(dirname "$target")"
  backup "$target"
  run ln -s "$dest" "$target"
  echo "link    $target -> $dest"
}

restore() { # restore <target>: put the newest backup back, if there is one
  local b
  b="$(newest_backup "$1")"
  if [ -n "$b" ]; then
    run mv "$b" "$1"
    echo "restore $1 from $b"
  fi
}

if [ "$UNINSTALL" = 1 ]; then
  for target in "$HOME/.codex/AGENTS.md" "$HOME/.gemini/GEMINI.md"; do
    if [ -L "$target" ] && [ "$(readlink "$target")" = "$CANON" ]; then
      run rm "$target"; echo "unlink  $target"; restore "$target"
    elif [ -e "$target" ]; then
      echo "skip    $target (not installed by this script)"
    fi
  done
  if [ -f "$CLAUDE_MD" ] && [ "$(cat "$CLAUDE_MD")" = "$CLAUDE_CONTENT" ]; then
    run rm "$CLAUDE_MD"; echo "remove  $CLAUDE_MD"; restore "$CLAUDE_MD"
  elif [ -f "$CLAUDE_MD" ] && grep -qxF "$IMPORT_LINE" "$CLAUDE_MD"; then
    echo "manual  $CLAUDE_MD was edited after install. Remove the line $IMPORT_LINE by hand."
  fi
  if is_generated "$CANON"; then
    run rm "$CANON"; echo "remove  $CANON"; restore "$CANON"
  elif [ -e "$CANON" ]; then
    echo "skip    $CANON (not generated by this script)"
  fi
  echo "manual  Cursor: remove the rules from Settings > Rules > User Rules."
else
  # 1. Generate the one file every agent reads: public rules, then private rules.
  CONTENT="$HEADER"$'\n\n'"$(cat "$PUBLIC")"
  if [ -f "$LOCAL" ]; then CONTENT="$CONTENT"$'\n\n'"$(cat "$LOCAL")"; fi
  lines=$(printf '%s\n' "$CONTENT" | awk 'END { print NR }')
  if is_generated "$CANON" && [ "$(cat "$CANON")" = "$CONTENT" ]; then
    echo "ok      $CANON"
  else
    run mkdir -p "$(dirname "$CANON")"
    if ! is_generated "$CANON"; then backup "$CANON"; fi
    if [ "$DRY_RUN" = 1 ]; then echo "  would: write $CANON ($lines lines)"; else printf '%s\n' "$CONTENT" > "$CANON"; fi
    note=""
    if [ -f "$LOCAL" ]; then note=", with private rules"; fi
    echo "write   $CANON ($lines lines$note)"
  fi
  # The header adds two lines to the 150-line budget of the rules themselves.
  if [ "$lines" -gt 152 ]; then echo "warn    $CANON has $lines lines. Keep the rules under 150."; fi
  # 2. Codex CLI and app read ~/.codex/AGENTS.md. Codex has no imports, so a link.
  link "$HOME/.codex/AGENTS.md" "$CANON"
  # 3. Gemini CLI and Antigravity read ~/.gemini/GEMINI.md.
  link "$HOME/.gemini/GEMINI.md" "$CANON"
  # 4. Claude Code: ~/.claude/CLAUDE.md imports the file, so Claude-only settings can stay beside it.
  if [ -f "$CLAUDE_MD" ] && grep -qxF "$IMPORT_LINE" "$CLAUDE_MD"; then
    echo "ok      $CLAUDE_MD"
  else
    run mkdir -p "$(dirname "$CLAUDE_MD")"
    if [ -e "$CLAUDE_MD" ]; then
      run cp "$CLAUDE_MD" "$CLAUDE_MD.bak.$STAMP"
      echo "backup  $CLAUDE_MD.bak.$STAMP"
    fi
    if [ "$DRY_RUN" = 1 ]; then echo "  would: write $CLAUDE_MD with the line $IMPORT_LINE"; else printf '%s\n' "$CLAUDE_CONTENT" > "$CLAUDE_MD"; fi
    echo "write   $CLAUDE_MD"
  fi
  # 5. Cursor has no global rules file. Its User Rules live in the app settings.
  echo "manual  Cursor: paste $CANON into Settings > Rules > User Rules. Paste again after each change."
fi

if [ "$DRY_RUN" = 1 ]; then echo "Dry run. Nothing changed."; fi
exit 0
